-- Disable RLS completely for testing
-- Run this in your Supabase SQL Editor

ALTER TABLE venues DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE trigger_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE override_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE parking_areas DISABLE ROW LEVEL SECURITY;
ALTER TABLE roads DISABLE ROW LEVEL SECURITY;
