import type { Venue, Booking, ParkingArea, Road } from "./types"

export const SEED_VENUES: Venue[] = [
  {
    id: "v1",
    name: "Cape Town Stadium",
    type: "outdoor",
    maxPopulation: 68000,
    ownerName: "City of Cape Town",
    ownerContact: "stadium@capetown.gov.za",
    address: "Fritz Sonnenberg Road, Green Point, Cape Town",
    image: "/images/venues/cape-town-stadium.jpg",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "v2",
    name: "Shared Fields",
    type: "outdoor",
    maxPopulation: 5000,
    ownerName: "City of Cape Town",
    ownerContact: "fields@capetown.gov.za",
    address: "Green Point Common, Cape Town",
    image: "/images/venues/shared-fields.jpg",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "v3",
    name: "Green Point Cricket Club",
    type: "hybrid",
    maxPopulation: 1000,
    ownerName: "Green Point Cricket Club",
    ownerContact: "events@gpcc.co.za",
    address: "Queen's Road, Green Point, Cape Town",
    image: "/images/venues/green-point-cricket-club.jpg",
    createdAt: "2025-02-01T08:00:00Z",
  },
  {
    id: "v4",
    name: "Green Point A Track",
    type: "outdoor",
    maxPopulation: 7000,
    ownerName: "City of Cape Town",
    ownerContact: "athletics@capetown.gov.za",
    address: "Green Point, Cape Town",
    image: "/images/venues/green-point-a-track.jpg",
    createdAt: "2025-02-10T08:00:00Z",
  },
  {
    id: "v5",
    name: "Hamilton Rugby Club",
    type: "hybrid",
    maxPopulation: 12000,
    ownerName: "Hamilton Rugby Club",
    ownerContact: "events@hamiltonrfc.co.za",
    address: "Hamilton Road, Green Point, Cape Town",
    image: "/images/venues/hamilton-rugby-club.jpg",
    createdAt: "2025-03-01T08:00:00Z",
  },
  {
    id: "v6",
    name: "Green Point Urban Park",
    type: "outdoor",
    maxPopulation: 90000,
    ownerName: "City of Cape Town",
    ownerContact: "parks@capetown.gov.za",
    address: "1 Fritz Sonnenberg Road, Green Point, Cape Town",
    image: "/images/venues/green-point-urban-park.jpg",
    createdAt: "2025-03-10T08:00:00Z",
  },
  {
    id: "v7",
    name: "Green Point Athletics Stadium",
    type: "outdoor",
    maxPopulation: 7000,
    ownerName: "City of Cape Town",
    ownerContact: "athletics@capetown.gov.za",
    address: "Green Point, Cape Town",
    image: "/images/venues/green-point-athletics-stadium.jpg",
    createdAt: "2025-04-01T08:00:00Z",
  },
]

export const SEED_BOOKINGS: Booking[] = [
  {
    id: "b1",
    venueId: "v1",
    title: "Cape Town Sevens Rugby",
    description: "Annual HSBC World Rugby Sevens tournament at Cape Town Stadium",
    date: "2026-03-14",
    startTime: "09:00",
    endTime: "21:00",
    expectedAttendance: 55000,
    riskLevel: "high",
    amplifiedNoise: true,
    liquorLicense: true,
    organizer: "SA Rugby",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-01-10T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b2",
    venueId: "v5",
    title: "Cape Town 10s Festival",
    description: "Multi-day rugby tens festival with live music and food stalls",
    date: "2026-03-15",
    startTime: "10:00",
    endTime: "23:00",
    expectedAttendance: 10000,
    riskLevel: "high",
    amplifiedNoise: true,
    liquorLicense: true,
    organizer: "Hamilton Events",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-01-15T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b3",
    venueId: "v3",
    title: "Corporate Cricket Day",
    description: "Invitational corporate cricket match and networking event on the clubhouse deck",
    date: "2026-03-20",
    startTime: "10:00",
    endTime: "17:00",
    expectedAttendance: 150,
    riskLevel: "low",
    amplifiedNoise: false,
    liquorLicense: true,
    organizer: "Cape Business Alliance",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-01-20T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b4",
    venueId: "v7",
    title: "Schools Athletics Championship",
    description: "Western Cape schools athletics championship event",
    date: "2026-03-21",
    startTime: "08:00",
    endTime: "16:00",
    expectedAttendance: 4500,
    riskLevel: "low",
    amplifiedNoise: true,
    liquorLicense: false,
    organizer: "WC Schools Athletics",
    status: "pending",
    conflicts: [],
    createdAt: "2026-02-01T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b5",
    venueId: "v1",
    title: "International Concert",
    description: "International artist live concert at Cape Town Stadium",
    date: "2026-03-14",
    startTime: "18:00",
    endTime: "23:00",
    expectedAttendance: 45000,
    riskLevel: "high",
    amplifiedNoise: true,
    liquorLicense: true,
    organizer: "Big Concerts",
    status: "override",
    overrideReason: "Approved by Events Director - concert follows rugby and uses separate staging",
    overriddenBy: "Admin J. Smith",
    overriddenAt: "2026-02-05T10:00:00Z",
    conflicts: [
      {
        type: "venue_conflict",
        severity: "critical",
        message: "Overlaps with 'Cape Town Sevens Rugby' at Cape Town Stadium (09:00-21:00)",
        suggestion: "Consider rescheduling to a different date or using an alternative venue",
        relatedBookingId: "b1",
      },
    ],
    createdAt: "2026-02-05T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b6",
    venueId: "v6",
    title: "Green Point Park Run",
    description: "Weekly community park run event through the Urban Park",
    date: "2026-03-21",
    startTime: "07:00",
    endTime: "09:00",
    expectedAttendance: 800,
    riskLevel: "low",
    amplifiedNoise: false,
    liquorLicense: false,
    organizer: "Parkrun SA",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-02-10T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b7",
    venueId: "v2",
    title: "Community Football Tournament",
    description: "Local community five-a-side football tournament on shared fields",
    date: "2026-03-22",
    startTime: "09:00",
    endTime: "17:00",
    expectedAttendance: 2000,
    riskLevel: "medium",
    amplifiedNoise: true,
    liquorLicense: false,
    organizer: "Green Point Sports Council",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-02-15T08:00:00Z",
    createdBy: "operator",
  },
  {
    id: "b8",
    venueId: "v6",
    title: "Outdoor Yoga Festival",
    description: "Wellness and yoga festival in the amphitheatre area of the Urban Park",
    date: "2026-03-22",
    startTime: "06:00",
    endTime: "12:00",
    expectedAttendance: 300,
    riskLevel: "low",
    amplifiedNoise: false,
    liquorLicense: false,
    organizer: "Cape Wellness Co",
    status: "confirmed",
    conflicts: [],
    createdAt: "2026-02-18T08:00:00Z",
    createdBy: "operator",
  },
]

export const SEED_PARKING_AREAS: ParkingArea[] = [
  {
    id: "p1",
    name: "Stadium Parking Precinct",
    totalSpaces: 4000,
    allocatedSpaces: 2800,
    location: "Adjacent to Cape Town Stadium, Fritz Sonnenberg Road",
    linkedVenueIds: ["v1"],
  },
  {
    id: "p2",
    name: "Green Point Common Lot",
    totalSpaces: 1200,
    allocatedSpaces: 600,
    location: "Green Point Common, off Beach Road",
    linkedVenueIds: ["v2", "v4", "v7"],
  },
  {
    id: "p3",
    name: "Hamilton Street Parking",
    totalSpaces: 300,
    allocatedSpaces: 150,
    location: "Hamilton Road, Green Point",
    linkedVenueIds: ["v3", "v5"],
  },
  {
    id: "p4",
    name: "Urban Park Visitor Parking",
    totalSpaces: 200,
    allocatedSpaces: 80,
    location: "Fritz Sonnenberg Road, adjacent to Urban Park entrance",
    linkedVenueIds: ["v6"],
  },
]

export const SEED_ROADS: Road[] = [
  {
    id: "r1",
    name: "Fritz Sonnenberg Road (Stadium Precinct)",
    status: "open",
    linkedVenueIds: ["v1", "v6"],
  },
  {
    id: "r2",
    name: "Beach Road (Green Point Section)",
    status: "restricted",
    closureReason: "Cape Town Sevens event traffic management",
    closureStart: "2026-03-14",
    closureEnd: "2026-03-15",
    linkedVenueIds: ["v1", "v2"],
  },
  {
    id: "r3",
    name: "Queen's Road (Cricket & Rugby Zone)",
    status: "open",
    linkedVenueIds: ["v3", "v5"],
  },
  {
    id: "r4",
    name: "Helen Suzman Boulevard",
    status: "open",
    linkedVenueIds: ["v4", "v7"],
  },
]
